version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://Free:Willy@db:5432/wiki
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: Free
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: library/postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: Free
      POSTGRES_PASSWORD: Willy
    volumes:
      - "./postgres/init:/docker-entrypoint-initdb.d"
