version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywl

jobs:
  sample:
    machine:
      # Try to use the latest Machine image if possible
      # See https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2204:2022.04.1
    steps:
      - run:
          name: check dependencies
          command: |
            docker version
            
            which java && java --version
            
            # redis-cli not included
            which redis-cli || true

            # mysql CLI not included
            which mysql || true
      - run:
          name: Run Redis
          command: |
            docker run -p "6379:6379" --name redis circleci/redis:5.0.6-alpine3.10
          background: true
      - run:
          name: Run MySQL
          command: |
            docker run -p "3306:3306" --name mysql circleci/mysql:5.7.20
          background: true
      - run:
          name: Install dependencies
          command: |
            # just an example of installing extra dependencies
            sudo apt-get update -y
            sudo apt-get install -y mysql-client
      - run:
          name: Wait on Redis server to be ready
          command: |
            N=8
            while [ $N -gt 0 ]
            do
              if $(nc -z 127.0.0.1 6379); then
                echo "Redis is up!"
                exit 0
              fi
              echo "Redis is unavailable at port 6379; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
      - run:
          name: Wait on MySQL server to be ready
          command: |
            # see env vars on this MySQL container
            docker container inspect mysql | jq ".[0].Config.Env"

            N=8
            while [ $N -gt 0 ]
            do
              if $(nc -z 127.0.0.1 3306); then
                echo "MySQL is up!"
                exit 0
              fi
              echo "MySQL is unavailable at port 3306; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
workflows:
  test:
    jobs:
      - sample
