version: 2.1

jobs:
  stats:
    docker:
      - image: cimg/base:stable
      - image: scylladb/scylla:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: |
            docker stats --all --format "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}"
          background: true
      - run: 
          command: |
            sleep 2m

workflows:
  sidecar_monitoring:
    jobs:
      - stats
