version: 2.1

jobs:
  stats:
    docker:
      - image: cimg/base:stable
      - image: scylladb/scylla:latest
    steps:
      - checkout
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always

workflows:
  sidecar_monitoring:
    jobs:
      - stats
