version: 2.1

jobs:
  mount-sock:
    machine:
      # Try to use the latest Machine image if possible
      # See https://circleci.com/docs/2.0/configuration-reference#available-linux-machine-images
      image: ubuntu-2004:202201-02
    steps:
      - run: |
          docker info
          env | grep DOCKER_
      - run:
          name: Spin up Redis at 6379
          command: |
            docker container run -p 6379:6379 --name=redis redis
          background: true
      - run:
          name: Spin up Portainer at 9000
          command: |
            docker container run -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer
          background: true
      - run:
          name: check containers
          command: |
            sleep 10
            docker ps
      - run:
          name: Create admin account on Portainer
          command: |
            curl -v -X POST -d '{"username":"admin","password":"quickbrownfox"}' -H 'Content-Type: application/json' -H 'Origin: http://localhost:9000'  http://localhost:9000/api/auth

workflows:
  sock:
    jobs:
      - mount-sock
