
version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          name: "Build Docker Images"
          command: |
            # ./build-images.sh
            # docker images
            docker login -u jkzilla -p dckr_pat_TSB1Z-i_8bAZJ0X797lMllQFGLw
            docker build -t jkzilla/ci-demo-docker-primary:0.0.1 .
            docker push jkzilla/ci-demo-docker-primary:0.0.1
      - run:
          name: "Install Test Prerequisites"
          command: |
            echo $DOCKER_PASS