version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build_with_dlc_aws_ecr:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_ECR_ACCOUNT_URL: 660990364978.dkr.ecr.us-east-1.amazonaws.com
      AWS_REGION: us-east-1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          repo: kelvintaywl/fancy-nginx-cached
          dockerfile: ./Dockerfile
          tag: stable,latest
      - aws-ecr/build-and-push-image:
          repo: kelvin/fancy-nginx
          dockerfile: ./Dockerfile

workflows:
  # Builds a custom image with DLC
  # and publishes to AWS ECR!
  build_publish_dlc_aws_ecr:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: kelvintaywl/fancy-nginx-cached
          dockerfile: ./Dockerfile
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
