---
version: 2.1

parameters:
  deployment-destination:
    type: string
    default: ""
  allocation-service-modified:
    type: boolean
    default: false
  delivery-service-modified:
    type: boolean
    default: false
  ingest-service-modified:
    type: boolean
    default: false
  qualification-service-modified:
    type: boolean
    default: false
  shared-library-modified:
    type: boolean
    default: false


anchors:
  env-executions:
    - &circle-ci-base
      docker:
        - image: cimg/base:stable
      resource_class: small
    - &circle-ci-python-node
      docker:
        - image: cimg/python:3.11.5-node
      resource_class: small
    - &machine-ubuntu
      machine:
        image: ubuntu-2204:2022.04.2
        docker_layer_caching: true

commands:
  build:
    parameters:
      target:
        type: string
        default: "build"
    steps:
      - checkout
      - run:
          command: |
            docker buildx build \
            --progress plain \
            --target << parameters.target >> \
            --tag << parameters.target >> \
            .

  just:
    parameters:
      command:
        type: string
      target:
        type: string
    steps:
      - build:
          target: << parameters.target >>
      - run:
          command: |
            docker run \
            << parameters.target >> just << parameters.command >>

  semantic-release-install:
    parameters:
      project-context:
        type: string
    steps:
      - run:
          command: |
            npm install --loglevel=error \
              @semantic-release/commit-analyzer@9.0.2 \
              @semantic-release/changelog@6.0.3 \
              @semantic-release/exec@6.0.3 \
              @semantic-release/git@10.0.1 \
              @semantic-release/github@8.1.0 \
              @semantic-release/release-notes-generator@10.0.3 \
              semantic-release@22.0.5 \
              semantic-release-monorepo@7.0.5
          working_directory: << parameters.project-context >>

jobs:
  test:
    parameters:
      target:
        type: string
      test-command:
        type: string
        default: circleci-test
    <<: *machine-ubuntu
    steps:
      - run:
          command: 
            mkdir -p /app/test-results
      - store_test_results:
          path: /app/test-results


workflows:
  ingest-service:
    jobs:
      - test:
          target: shared