version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::483285841698:role/jkg
                role_session_name: "jkg-session"
          dockerfile: Dockerfile
          push_image: true
          region: 'us-east-2'
          repo: jkg
          repo_policy_path: ./policy.json
          tag: latest,myECRRepoTag
          context: aws
