version: 2.1

jobs:
  show-docker-envs:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - setup_remote_docker:
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.7
      - run:
          name: check DOCKER_ env vars
          command: |
            (env | grep DOCKER_) || echo 'no DOCKER_* env vars set'

workflows:
  # Builds a custom image,
  # spins it up for tests,
  # and publishes to Docker Hub!
  envs:
    jobs:
      - show-docker-envs
